In [96]:
from PIL import Image
import os
import matplotlib.pyplot as plt

#load images convert to RGB and resize to 48x48 pixels

target_size = 48
input_dir = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset1\\part1" # change to your input directory obv

def load_images(input_dir, target_size):
    
    image_names = os.listdir(input_dir)
    path = os.path.join(input_dir, image_names[0])
    img = Image.open(path).convert("RGB")

    images = [Image.open(os.path.join(input_dir, name)).convert("RGB").resize((target_size, target_size), Image.LANCZOS) for name in image_names]

    return image_names, images

def plot_images(img):
    plt.imshow(img)
    plt.axis('off')
    plt.show()


In [97]:
image_names, images = load_images(input_dir, target_size) #this takes a while lol

In [90]:
import numpy as np
# flatten the images to 1D arrays

pixels = np.array([np.array(images[0]).reshape(-1) for img in images])
print(pixels.shape)

(10137, 6912)


In [86]:
from sklearn.preprocessing import OneHotEncoder
#getting labels from filenames

base = np.array([names.split(".")[0] for names in image_names]) # swap image_names here for for part 2 and 3 if needed
parts = np.array([name.split("_")[:3] for name in base])

age = np.array([int(part[0]) for part in parts]) # 0-116 int
gender = np.array([part[1] for part in parts]) # 0 = M, 1 = F
ethnicity = np.array([part[2] for part in parts]) # 0 = White, 1 = Black, 2 = Asian, 3 = Indian, 4 = Other

enc = OneHotEncoder(sparse_output=False)

age_norm = age / 116.0
gender_norm = gender
ethnicity_norm = enc.fit_transform(ethnicity.reshape(-1, 1)) # one hot encode

print(age_norm)
print(gender_norm)
print(ethnicity_norm)

[0.86206897 0.86206897 0.86206897 ... 0.07758621 0.07758621 0.07758621]
['1' '1' '1' ... '1' '1' '1']
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [91]:
input_dir_angry = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\angry"
input_dir_disgust = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\disgust"
input_dir_fear = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\fear"
input_dir_happy = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\happy"
input_dir_neutral = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\neutral"
input_dir_sad = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\sad"
input_dir_surprise = "C:\\Users\\ThinkPad\\Desktop\\BME\\4. szemeszter\\Machine learning\\project\\dataset2\\train\\surprise"

image_names_angry, images_angry = load_images(input_dir_angry, target_size)
image_names_disgust, images_disgust = load_images(input_dir_disgust, target_size)
image_names_fear, images_fear = load_images(input_dir_fear, target_size)
image_names_happy, images_happy = load_images(input_dir_happy, target_size)
image_names_neutral, images_neutral = load_images(input_dir_neutral, target_size)
image_names_sad, images_sad = load_images(input_dir_sad, target_size)
image_names_surprise, images_surprise = load_images(input_dir_surprise, target_size)

images_emotions = np.concat(([images_angry, images_disgust, images_fear, images_happy, images_neutral, images_sad, images_surprise]))


In [ ]:

pixels_emotions = np.array([np.array(images_emotions[0]).reshape(-1) for img in images_emotions])


labels = np.concat([np.ones(len(images_angry)),np.ones(len(images_disgust))*2,np.ones(len(images_fear))*3,np.ones(len(images_happy))*4,np.ones(len(images_neutral))*5,np.ones(len(images_sad))*6,np.ones(len(images_surprise))*7])
labels_norm = enc.fit_transform(labels.reshape(-1, 1))  # one hot encode

print(pixels_emotions[0])

[229 233 239 ... 255 255 255]
